### ISSUE TITLE
GCP - HA_via_api does not excute onboard script

### ISSUE THREAD

**Issue by densnoigaskogen** [JeffGiroux/f5_terraform#12] opened 2021-02-10 15:12 UTC
Hi Jeff, we are deploying the templates on GCP using terraform version v0.13.5.
BYOL image: f5-bigip-15-1-0-4-0-0-6-byol-all-modules-2boot-loc-00618231635
BIGIP VEs are created successfully, however, the onborad scripts were not being exceuted.
![image](https://user-images.githubusercontent.com/33136996/107528601-4fb0ad80-6bba-11eb-9bd0-bb39ad60ad45.png)

![image](https://user-images.githubusercontent.com/33136996/107528772-7c64c500-6bba-11eb-8b49-cc1e86eb05a1.png)

![image](https://user-images.githubusercontent.com/33136996/107528840-8f779500-6bba-11eb-9e04-7353201a9706.png)

I have re-deployed several times (3 times), still got the same results. Do you know what could be possible cause?

**Comment by JeffGiroux** [comment] 2021-02-10 15:42
I would first start by digging into the onboarding logs. You can find those in the directory based on your deployment variables and values. Look at the variables.tf file in the repo to see the logging directory.

https://github.com/JeffGiroux/f5_terraform/blob/main/GCP/HA_via_api/variables.tf

snippet
```
variable onboard_log { default = "/var/log/cloud/onboard.log" }
```

You will want to login to the device, go to the cloud directory, then review log file for errors. You should be able match some of the logging lines with the echo statements in the onboard.tpl in order to follow logical flow when you do find the error. 

I would say...double check your permissions. Make sure your infrastructure, networks, firewalls rules, etc allow proper outbound communication to the internet in order to download the cloud packages. If you don't have proper networks and rules setup, then I would check your infra setup first. For that, I would recommend starting with my infra-only folder to give you a good base network. It has the required network setup and needed firewall rules.

Parent - https://github.com/JeffGiroux/f5_terraform/tree/main/GCP
infra only - https://github.com/JeffGiroux/f5_terraform/tree/main/GCP/Infrastructure-only

Once you have a known working network VPC setup, then proceed with HA via API templates...
https://github.com/JeffGiroux/f5_terraform/tree/main/GCP/HA_via_api

**Comment by densnoigaskogen** [comment] 2021-02-10 16:13
thanks for your prompt support!
We did use your infra template to build VPCs and FW rules set up correctly.
Regarding the log file location, we kept it as default as well:
 variable onboard_log { default = "/var/log/cloud/onboard.log" }

However, it does not seem like the directory was being created in VM.
![image](https://user-images.githubusercontent.com/33136996/107537404-1b8dba80-6bc3-11eb-9fc9-9b12cbc99422.png)

**Comment by JeffGiroux** [comment] 2021-02-10 16:37
To use normal linux CLI stuff, you have to enter bash mode first. At the tmos prompt, simply type

```
bash
```

Then you're at normal bash prompt, can cd to directories, and more.

Also, good to know about your base setup using the infra-only folder. One less troubleshooting step :)

**Comment by densnoigaskogen** [comment] 2021-02-10 16:52
thanks. 
There is no folder called 'cloud' being created under /var/log either.
![image](https://user-images.githubusercontent.com/33136996/107542010-06fff100-6bc8-11eb-89ed-99664306109d.png)

**Comment by JeffGiroux** [comment] 2021-02-10 16:59
Let's get your local F5 account team involved. What is your company? I'll look up the F5 account team to help make the intro. As for the cloud directory not being created...it's all about reverse engineering the onboard.tpl scripts as mentioned before :)

Look in onboard.tpl to determine where the 'cloud' folder is being created. If you're saying it's not there, then it failed to be created by the onboard.tpl script. And...based on the script, that folder is supposed to create first thing.

```
#!/bin/bash
source /usr/lib/bigstart/bigip-ready-functions

# BIG-IP ONBOARD SCRIPT

mkdir -p /config/cloud
mkdir -p /var/log/cloud
```

Since it doesn't this tells me your onboard.tpl is not executing which means the Google VM instance is not being initiated correctly. Then I looked over your opening comment again on this issue and noticed you're using a 2boot slot which means BYOL licensing.

Two questions:
1. Did you follow the BYOL instructions in the README?
https://github.com/JeffGiroux/f5_terraform/tree/main/GCP/HA_via_api#byol-licensing

2. What is your company name so I can look up your F5 account team to make intros and continue troubleshooting.

**Comment by densnoigaskogen** [comment] 2021-02-10 17:12
thank you very much for helping out.
Our company name is xxxxxxx. (I will remove the name from the thread after your confirmation :) )
Regarding the modification on the script for BYOL, yes, I modified them accordingly both in variables.tf and do.json file.
Below is snippet from do.json file:
![image](https://user-images.githubusercontent.com/33136996/107545383-83e09a00-6bcb-11eb-8f52-f75bd5caf7fd.png)

**Comment by JeffGiroux** [comment] 2021-02-10 17:25
I have blasted to our internal SE list to find the team for this account. In the mean time, can you send me your work email? Once I find the team, I'll sync everyone up. Send to my work email.

As for further troubleshooting, would be helpful to know of any other changes made to the default repo. Also suggestion, try to deploy the repo as-is with a PAYG instance instead. As another test, and more speedy, try the standalone deployment first. That way, only one instance waiting to deploy. If you get successful standalone, then move to HA.

**Comment by densnoigaskogen** [comment] 2021-02-10 17:30
it sounds perfect! We will communicate further  via emails.
Good idea to play with PAYG, we were actually thinking about doing that as well.

**Comment by JeffGiroux** [comment] 2021-02-10 22:36
Quick troubleshooting form repo owner...me :)

1. Tested repo-as is with terraform 0.12.29, payg, standalone. Works great. Tested autoscale too.
2. Update BIG-IP version from 15.1.0.4 to 15.1.2.1 in variables.tf. Redeployed payg standalone, ha-via api, a few others, works great.
3. Update F5 toolchain RPMs (as3, do, ts, cfe) to latest. Redeployed payg various. Worked great.
4. Update terraform required version to 0.14+ (also tested 0.13...no issues), and google provider. Works great on PAYG
5. Then tested BYOL. Still works great. Onboard script (VM init startup) fired each time, created cloud directory, ran through RPM installs and POSTed all declarations.

Will wait to hear back from your payg standalone testing to close this ticket or not depending on root cause.

**Comment by JeffGiroux** [comment] 2021-05-25 05:08
No response

**Closed as completed by JeffGiroux** 2021-05-25 05:08 UTC
